"""created_at

Revision ID: 082dfb2d2dd8
Revises: 1f8a2c4980b7
Create Date: 2018-06-09 12:50:28.456301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '082dfb2d2dd8'
down_revision = '1f8a2c4980b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'created_at')
    # ### end Alembic commands ###
