"""add permanent id

Revision ID: 1d12b23f2369
Revises: 706b073d0f2f
Create Date: 2018-05-30 16:44:22.908953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d12b23f2369'
down_revision = '706b073d0f2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('permanent_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'contents', ['permanent_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contents', type_='unique')
    op.drop_column('contents', 'permanent_id')
    # ### end Alembic commands ###
