"""add enums

Revision ID: 1d82d8d885eb
Revises: adcbf279704c
Create Date: 2018-06-13 21:01:08.169536

"""
from alembic import op
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa


import sys
import os

sys.path.append(os.getcwd())

import enums


# revision identifiers, used by Alembic.
revision = '1d82d8d885eb'
down_revision = 'adcbf279704c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    data_origin = postgresql.ENUM(enums.DataOriginEnum, name='dataoriginenum')
    data_origin.create(op.get_bind())


    op.add_column('contents', sa.Column('source', sa.Enum(enums.DataOriginEnum, name='dataoriginenum', create_type=False), nullable=True))
    op.drop_column('contents', 'origin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('origin', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.execute("ALTER TYPE dataoriginenum ADD VALUE IF NOT EXISTS 'DOGDRIP'")
    op.drop_column('contents', 'source')

    data_origin = postgresql.ENUM(enums.DataOriginEnum, name='dataoriginenum')
    data_origin.drop(op.get_bind())
    # ### end Alembic commands ###
