"""add origin

Revision ID: 1f8a2c4980b7
Revises: 1d12b23f2369
Create Date: 2018-06-01 00:20:29.686249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f8a2c4980b7'
down_revision = '1d12b23f2369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('origin', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'origin')
    # ### end Alembic commands ###
