"""remove permanent id in comment

Revision ID: 376490409b0c
Revises: 81f646dfd0af
Create Date: 2018-07-03 15:16:35.589190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376490409b0c'
down_revision = '81f646dfd0af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_permanent_id_key', 'comments', type_='unique')
    op.drop_column('comments', 'permanent_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('permanent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('comments_permanent_id_key', 'comments', ['permanent_id'])
    # ### end Alembic commands ###
