"""add user and enums

Revision ID: 50a3740c4cfd
Revises: adcbf279704c
Create Date: 2018-06-13 20:31:29.876320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50a3740c4cfd'
down_revision = 'adcbf279704c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signup_type', sa.Enum('NAVER', name='signuptypeenum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
