"""add data

Revision ID: 706b073d0f2f
Revises: 5aa4c7a48394
Create Date: 2018-05-26 10:30:59.758542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '706b073d0f2f'
down_revision = '5aa4c7a48394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('data', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'data')
    # ### end Alembic commands ###
