"""create boards

Revision ID: c86fc432bda5
Revises: b79eff990fc2
Create Date: 2018-09-12 13:53:26.054217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c86fc432bda5'
down_revision = 'b79eff990fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_uid_cid', 'showed_contents', ['id', 'cid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_uid_cid', table_name='showed_contents')
    op.drop_table('boards')
    # ### end Alembic commands ###
