"""update user and content

Revision ID: ce4f6114a5e2
Revises: 6c1969e36d78
Create Date: 2019-04-07 22:02:20.334172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce4f6114a5e2'
down_revision = '6c1969e36d78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('uid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contents', 'users', ['uid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contents', type_='foreignkey')
    op.drop_column('contents', 'uid')
    # ### end Alembic commands ###
