"""rollback

Revision ID: d24203a8933e
Revises: ce4f6114a5e2
Create Date: 2019-04-07 22:11:05.524066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd24203a8933e'
down_revision = 'ce4f6114a5e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contents_uid_fkey', 'contents', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('contents_uid_fkey', 'contents', 'users', ['uid'], ['id'])
    # ### end Alembic commands ###
