"""relationship to itselves

Revision ID: d34ed238f470
Revises: e205f17433d6
Create Date: 2018-06-17 18:35:49.856006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd34ed238f470'
down_revision = 'e205f17433d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'comments', ['permanent_id'])
    op.create_foreign_key(None, 'comments', 'comments', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='unique')
    # ### end Alembic commands ###
