"""modify comment

Revision ID: e205f17433d6
Revises: 0bda65545ab4
Create Date: 2018-06-17 11:33:50.439990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e205f17433d6'
down_revision = '0bda65545ab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('comments', sa.Column('name', sa.String(), nullable=True))
    op.add_column('comments', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('permanent_id', sa.Integer(), nullable=True))
    op.drop_column('comments', 'parent_comment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('parent_comment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'permanent_id')
    op.drop_column('comments', 'parent_id')
    op.drop_column('comments', 'name')
    op.drop_column('comments', 'created_at')
    # ### end Alembic commands ###
