"""modify Base

Revision ID: ee6aec241819
Revises: 0a6fa524f510
Create Date: 2019-04-12 17:50:01.446597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee6aec241819'
down_revision = '0a6fa524f510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('contents', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('showed_contents', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('wards', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wards', 'updated_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('showed_contents', 'updated_at')
    op.drop_column('contents', 'updated_at')
    op.drop_column('comments', 'updated_at')
    # ### end Alembic commands ###
