"""modify column name

Revision ID: f364d8472e64
Revises: d65b85069803
Create Date: 2018-06-13 21:32:21.060571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f364d8472e64'
down_revision = 'd65b85069803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('origin', sa.Enum('DOGDRIP', name='dataoriginenum'), nullable=True))
    op.drop_column('contents', 'source')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('source', postgresql.ENUM('DOGDRIP', name='dataoriginenum'), autoincrement=False, nullable=True))
    op.drop_column('contents', 'origin')
    # ### end Alembic commands ###
